### ISSUE TITLE
NEED THE DATABASE OR STEPS FOR BEGINNER

### ISSUE THREAD

**Issue by Chintangandhi007** [rahulsahay19/MovieReview-Angular-Prod#1]
Hi, 

Rahul,
 I am beginner in MVC 5 with Angular and SPA so can you provide the Database.. 

OR give the steps to Run this project in local machine ..

I don't know because If i forgot to follow some steps to run so kindly provide the DAtabase & Steps to run code on local machine...

**Comment by rahulsahay19** [comment]
Hi, 

This follows the code first approach, therefore, at first build it will build the database with seed values. Only thing which you need to do is make appsettings perfect in terms of connection string and one other place in code itself. Even then, if you need db. I have uploaded the .bak file in the repository. You Can refer that.

Thanks,
Rahul
